name: 'GitHub Push'
description: 'Pushing to GitHub repository local changes'
author: 'ad-m'
branding:
  icon: upload-cloud
  color: green
inputs:
  github_token:
    description: 'GitHub token or PAT token'
    required: true
    default: ${{ github.token }}
  github_url:
    description: 'GitHub url or GitHub Enterprise url'
    required: true
    default: ${{ github.server_url }}
  repository:
    description: 'Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})'
    default: ''
    required: false
  branch:
    description: 'Destination branch to push changes'
    required: false
  force:
    description: 'Determines if force push is used'
    required: false
  pull_first:
    description: 'Determines if the action should pull before the execution of the push command'
    required: false
  fetch_and_merge:
    description: 'Determines if the action should fetch and merge before the execution of the push command'
    required: false
  tags:
    description: 'Determines if --tags is used'
    required: false
  directory:
    description: 'Directory to change to before pushing.'
    required: false
    default: '.'
runs:
  using: 'node12'
  main: 'start.js'
